using System;using System.Collections.Generic;using System.Diagnostics;using System.Drawing;using System.IO;using System.Linq;using System.Threading.Tasks;using System.Windows.Forms;
namespace AtmacaTeraBox{
static class Program{[STAThread]static void Main(){Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Application.Run(new F());}}
class F:Form{
TextBox src=new TextBox(),dst=new TextBox();Button bs=new Button(),bd=new Button(),go=new Button();ComboBox size=new ComboBox();CheckBox zip=new CheckBox(),test=new CheckBox();Label st=new Label();ProgressBar bar=new ProgressBar();
public F(){Text="ATMACA TeraBox Hazırlayıcı";Width=850;Height=470;StartPosition=FormStartPosition.CenterScreen;Font=new Font("Segoe UI",10);BackColor=Color.FromArgb(247,249,252);
var h=new Panel{Dock=DockStyle.Top,Height=75,BackColor=Color.FromArgb(9,37,74)};h.Controls.Add(new Label{Text="ATMACA TERABOX HAZIRLAYICI",ForeColor=Color.FromArgb(255,210,0),Font=new Font("Segoe UI",18,FontStyle.Bold),AutoSize=true,Left=22,Top=15});h.Controls.Add(new Label{Text="2 / 4 / 8 / 16 GB paketle • 7-Zip varsa arşivle ve test et",ForeColor=Color.WhiteSmoke,AutoSize=true,Left=25,Top=49});Controls.Add(h);
var p=new Panel{Dock=DockStyle.Fill,Padding=new Padding(22)};Controls.Add(p);
p.Controls.Add(new Label{Text="Kaynak klasör",AutoSize=true,Left=0,Top=5});src.SetBounds(0,30,620,32);bs.Text="Seç";bs.SetBounds(635,29,105,34);bs.BackColor=Color.FromArgb(255,210,0);bs.Click+=(s,e)=>Pick(src);p.Controls.Add(src);p.Controls.Add(bs);
p.Controls.Add(new Label{Text="Çıktı klasörü",AutoSize=true,Left=0,Top=73});dst.SetBounds(0,98,620,32);bd.Text="Seç";bd.SetBounds(635,97,105,34);bd.Click+=(s,e)=>Pick(dst);p.Controls.Add(dst);p.Controls.Add(bd);
p.Controls.Add(new Label{Text="Paket boyutu",AutoSize=true,Left=0,Top=145});size.DropDownStyle=ComboBoxStyle.DropDownList;size.Items.AddRange(new object[]{"2 GB","4 GB","8 GB","16 GB"});size.SelectedIndex=1;size.SetBounds(0,171,150,32);p.Controls.Add(size);
zip.Text="7-Zip varsa .7z oluştur";zip.Checked=true;zip.AutoSize=true;zip.SetBounds(180,171,220,28);p.Controls.Add(zip);
test.Text="Arşivi test et";test.Checked=true;test.AutoSize=true;test.SetBounds(420,171,150,28);p.Controls.Add(test);
go.Text="HAZIRLA";go.SetBounds(0,225,160,42);go.BackColor=Color.FromArgb(9,37,74);go.ForeColor=Color.White;go.Click+=async(s,e)=>await Run();p.Controls.Add(go);
bar.SetBounds(0,285,740,22);p.Controls.Add(bar);st.Text="Hazır.";st.SetBounds(0,320,740,55);st.AutoEllipsis=true;p.Controls.Add(st);}
void Pick(TextBox t){using(var d=new FolderBrowserDialog()){if(d.ShowDialog()==DialogResult.OK)t.Text=d.SelectedPath;}}
long Limit(){return new long[]{2,4,8,16}[size.SelectedIndex]*1024L*1024L*1024L;}
async Task Run(){if(!Directory.Exists(src.Text)){MessageBox.Show("Kaynak klasör bulunamadı.");return;}if(string.IsNullOrWhiteSpace(dst.Text)){MessageBox.Show("Çıktı klasörünü seç.");return;}Directory.CreateDirectory(dst.Text);go.Enabled=false;bar.Value=0;var pr=new Progress<Tuple<int,int,string>>(x=>{bar.Value=x.Item2==0?0:Math.Min(100,x.Item1*100/x.Item2);st.Text=x.Item3;});try{string m=await Task.Run(()=>Prepare(Limit(),pr));bar.Value=100;MessageBox.Show(m);st.Text=m;}finally{go.Enabled=true;}}
string Prepare(long limit,IProgress<Tuple<int,int,string>> pr){var files=Directory.EnumerateFiles(src.Text,"*",SearchOption.AllDirectories).Select(x=>new FileInfo(x)).OrderBy(x=>x.FullName,StringComparer.OrdinalIgnoreCase).ToList();if(files.Count==0)return "Dosya bulunamadı.";var packs=new List<List<FileInfo>>();var cur=new List<FileInfo>();long used=0;foreach(var f in files){if(cur.Count>0&&used+f.Length>limit){packs.Add(cur);cur=new List<FileInfo>();used=0;}cur.Add(f);used+=f.Length;}if(cur.Count>0)packs.Add(cur);string seven=Find7z();for(int i=0;i<packs.Count;i++){string folder=Path.Combine(dst.Text,"Paket_"+(i+1).ToString("D4"));Directory.CreateDirectory(folder);foreach(var f in packs[i]){string rel=Rel(src.Text,f.FullName);string target=Path.Combine(folder,rel);Directory.CreateDirectory(Path.GetDirectoryName(target));File.Copy(f.FullName,target,true);}pr.Report(Tuple.Create(i+1,packs.Count,"Paket "+(i+1)+" / "+packs.Count+" hazır."));if(zip.Checked&&seven!=null){string arc=folder+".7z";if(Exec(seven,"a -t7z -mx=5 -mmt=on \""+arc+"\" \""+folder+"\\*\"")!=0)return "7z oluşturulamadı.";if(test.Checked&&Exec(seven,"t \""+arc+"\"")!=0)return "7z testinde hata bulundu.";}}return packs.Count+" paket hazırlandı."+(zip.Checked?(seven==null?" 7-Zip bulunamadığı için klasör paketleri bırakıldı.":" 7z arşivleri oluşturuldu."):"");}
string Rel(string r,string f){r=Path.GetFullPath(r).TrimEnd('\\')+"\\";f=Path.GetFullPath(f);return f.StartsWith(r,StringComparison.OrdinalIgnoreCase)?f.Substring(r.Length):Path.GetFileName(f);}
string Find7z(){string[] a={Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles),"7-Zip","7z.exe"),Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86),"7-Zip","7z.exe"),Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"7z.exe")};return a.FirstOrDefault(File.Exists);}
int Exec(string e,string a){var p=new Process();p.StartInfo=new ProcessStartInfo(e,a){UseShellExecute=false,CreateNoWindow=true,WindowStyle=ProcessWindowStyle.Hidden};p.Start();p.WaitForExit();return p.ExitCode;}
}}
