using System;using System.Collections.Generic;using System.Drawing;using System.IO;using System.Threading;using System.Threading.Tasks;using System.Windows.Forms;
namespace AtmacaSearch{
static class Program{[STAThread]static void Main(){Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Application.Run(new F());}}
class F:Form{
TextBox root=new TextBox(),q=new TextBox();Button pick=new Button(),go=new Button(),stop=new Button(),open=new Button();CheckBox rec=new CheckBox();ListBox list=new ListBox();Label st=new Label();CancellationTokenSource cts;
public F(){Text="ATMACA Hızlı Dosya Arama";Width=900;Height=620;StartPosition=FormStartPosition.CenterScreen;Font=new Font("Segoe UI",10);BackColor=Color.FromArgb(247,249,252);
var h=new Panel{Dock=DockStyle.Top,Height=74,BackColor=Color.FromArgb(9,37,74)};h.Controls.Add(new Label{Text="ATMACA HIZLI DOSYA ARAMA",ForeColor=Color.FromArgb(255,210,0),Font=new Font("Segoe UI",18,FontStyle.Bold),AutoSize=true,Left=22,Top=16});Controls.Add(h);
var b=new Panel{Dock=DockStyle.Fill,Padding=new Padding(22)};Controls.Add(b);
b.Controls.Add(new Label{Text="Aranacak ana klasör",AutoSize=true,Left=0,Top=5});root.SetBounds(0,30,690,32);pick.Text="Seç";pick.SetBounds(705,29,105,34);pick.BackColor=Color.FromArgb(255,210,0);pick.Click+=(s,e)=>Pick();b.Controls.Add(root);b.Controls.Add(pick);
b.Controls.Add(new Label{Text="Dosya adında aranacak kelime",AutoSize=true,Left=0,Top=74});q.SetBounds(0,99,500,32);b.Controls.Add(q);rec.Text="Alt klasörleri tara";rec.Checked=true;rec.AutoSize=true;rec.SetBounds(520,101,170,26);b.Controls.Add(rec);
go.Text="ARA";go.SetBounds(0,148,120,38);go.BackColor=Color.FromArgb(9,37,74);go.ForeColor=Color.White;go.Click+=async(s,e)=>await Search();stop.Text="DURDUR";stop.SetBounds(135,148,110,38);stop.Enabled=false;stop.Click+=(s,e)=>cts?.Cancel();open.Text="SEÇİLİ DOSYANIN KLASÖRÜNÜ AÇ";open.SetBounds(260,148,280,38);open.Click+=(s,e)=>OpenSelected();b.Controls.Add(go);b.Controls.Add(stop);b.Controls.Add(open);
list.SetBounds(0,205,810,300);list.HorizontalScrollbar=true;list.DoubleClick+=(s,e)=>OpenSelected();b.Controls.Add(list);st.SetBounds(0,520,810,42);st.Text="Hazır.";b.Controls.Add(st);}
void Pick(){using(var d=new FolderBrowserDialog()){if(d.ShowDialog()==DialogResult.OK)root.Text=d.SelectedPath;}}
void Busy(bool x){go.Enabled=!x;pick.Enabled=!x;stop.Enabled=x;}
async Task Search(){if(!Directory.Exists(root.Text)){MessageBox.Show("Klasör bulunamadı.");return;}var term=q.Text.Trim();if(term.Length==0){MessageBox.Show("Aranacak kelimeyi yaz.");return;}list.Items.Clear();Busy(true);cts=new CancellationTokenSource();var pr=new Progress<Tuple<long,long,string>>(x=>st.Text="Taranan: "+x.Item1.ToString("N0")+" • Bulunan: "+x.Item2.ToString("N0")+" • "+x.Item3);try{var r=await Task.Run(()=>Find(root.Text,term,rec.Checked,cts.Token,pr));foreach(var x in r)list.Items.Add(x);st.Text=r.Count.ToString("N0")+" sonuç bulundu.";}catch(OperationCanceledException){st.Text="Arama durduruldu.";}finally{cts.Dispose();cts=null;Busy(false);}}
List<string> Find(string r,string term,bool recursive,CancellationToken t,IProgress<Tuple<long,long,string>> pr){var outp=new List<string>();var stack=new Stack<string>();stack.Push(r);long n=0;while(stack.Count>0){t.ThrowIfCancellationRequested();var d=stack.Pop();IEnumerable<string> files=Array.Empty<string>(),dirs=Array.Empty<string>();try{files=Directory.EnumerateFiles(d);}catch{}foreach(var f in files){t.ThrowIfCancellationRequested();n++;if(Path.GetFileName(f).IndexOf(term,StringComparison.OrdinalIgnoreCase)>=0)outp.Add(f);if(n%500==0)pr.Report(Tuple.Create(n,(long)outp.Count,f));}if(recursive){try{dirs=Directory.EnumerateDirectories(d);}catch{}foreach(var x in dirs)stack.Push(x);}}pr.Report(Tuple.Create(n,(long)outp.Count,r));return outp;}
void OpenSelected(){if(list.SelectedItem==null)return;var p=list.SelectedItem.ToString();if(!File.Exists(p))return;System.Diagnostics.Process.Start("explorer.exe","/select,\""+p+"\"");}
}}
