using System;using System.Collections.Generic;using System.Drawing;using System.IO;using System.Linq;using System.Threading.Tasks;using System.Windows.Forms;
namespace AtmacaKlasorAd{
static class Program{[STAThread]static void Main(){Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Application.Run(new F());}}
class F:Form{
TextBox root=new TextBox();Button pick=new Button(),scan=new Button(),rename=new Button();ListBox list=new ListBox();Label st=new Label();List<Tuple<string,string>> plan=new List<Tuple<string,string>>();
HashSet<string> media=new HashSet<string>(new[]{".jpg",".jpeg",".png",".webp",".bmp",".gif",".tif",".tiff",".heic",".heif",".avif",".jfif",".mp4",".mkv",".avi",".mov",".wmv",".m4v",".webm",".3gp",".mts",".m2ts",".ts",".flv",".mpeg",".mpg"},StringComparer.OrdinalIgnoreCase);
public F(){Text="ATMACA Klasör Adı Düzenleyici";Width=900;Height=630;StartPosition=FormStartPosition.CenterScreen;Font=new Font("Segoe UI",10);BackColor=Color.FromArgb(247,249,252);
var h=new Panel{Dock=DockStyle.Top,Height=74,BackColor=Color.FromArgb(9,37,74)};h.Controls.Add(new Label{Text="ATMACA KLASÖR ADI DÜZENLEYİCİ",ForeColor=Color.FromArgb(255,210,0),Font=new Font("Segoe UI",18,FontStyle.Bold),AutoSize=true,Left=22,Top=16});Controls.Add(h);
var p=new Panel{Dock=DockStyle.Fill,Padding=new Padding(22)};Controls.Add(p);root.SetBounds(0,12,690,32);pick.Text="Seç";pick.SetBounds(705,11,105,34);pick.BackColor=Color.FromArgb(255,210,0);pick.Click+=(s,e)=>Pick();p.Controls.Add(root);p.Controls.Add(pick);
scan.Text="TARA / ÖNİZLE";scan.SetBounds(0,62,150,38);scan.BackColor=Color.FromArgb(9,37,74);scan.ForeColor=Color.White;scan.Click+=async(s,e)=>await Scan();p.Controls.Add(scan);
rename.Text="KLASÖR ADLARINI UYGULA";rename.SetBounds(165,62,230,38);rename.BackColor=Color.FromArgb(255,210,0);rename.Enabled=false;rename.Click+=async(s,e)=>await Apply();p.Controls.Add(rename);
list.SetBounds(0,118,810,390);list.HorizontalScrollbar=true;p.Controls.Add(list);st.SetBounds(0,523,810,40);st.Text="Hazır.";p.Controls.Add(st);}
void Pick(){using(var d=new FolderBrowserDialog()){if(d.ShowDialog()==DialogResult.OK)root.Text=d.SelectedPath;}}
async Task Scan(){if(!Directory.Exists(root.Text)){MessageBox.Show("Klasör bulunamadı.");return;}scan.Enabled=false;rename.Enabled=false;list.Items.Clear();plan.Clear();st.Text="Taranıyor...";plan=await Task.Run(()=>Build());foreach(var x in plan)list.Items.Add(Path.GetFileName(x.Item1)+"  ->  "+Path.GetFileName(x.Item2));st.Text=plan.Count+" klasör için yeni ad hazır.";scan.Enabled=true;rename.Enabled=plan.Count>0;}
List<Tuple<string,string>> Build(){var r=new List<Tuple<string,string>>();IEnumerable<string> dirs;try{dirs=Directory.EnumerateDirectories(root.Text).ToList();}catch{return r;}var used=new HashSet<string>(StringComparer.OrdinalIgnoreCase);foreach(var d in dirs){string mediaFile=null;try{mediaFile=Directory.EnumerateFiles(d).FirstOrDefault(f=>media.Contains(Path.GetExtension(f)));}catch{}if(mediaFile==null)continue;var baseName=Safe(Path.GetFileNameWithoutExtension(mediaFile));if(string.IsNullOrWhiteSpace(baseName))baseName="Klasor";string name=baseName;int n=2;while(used.Contains(name)||Directory.Exists(Path.Combine(root.Text,name))&&!string.Equals(Path.Combine(root.Text,name),d,StringComparison.OrdinalIgnoreCase)){name=baseName+"_"+n++;}used.Add(name);r.Add(Tuple.Create(d,Path.Combine(root.Text,name)));}return r;}
string Safe(string s){foreach(var c in Path.GetInvalidFileNameChars())s=s.Replace(c,'_');return s.Trim().TrimEnd('.');}
async Task Apply(){if(plan.Count==0)return;if(MessageBox.Show(plan.Count+" klasör yeniden adlandırılacak. Aynı isimler _2, _3... ile ayrılacak. Devam?","ATMACA",MessageBoxButtons.YesNo)!=DialogResult.Yes)return;scan.Enabled=false;rename.Enabled=false;int n=await Task.Run(()=>{int k=0;foreach(var x in plan){try{if(!string.Equals(x.Item1,x.Item2,StringComparison.OrdinalIgnoreCase)){Directory.Move(x.Item1,x.Item2);k++;}}catch{}}return k;});MessageBox.Show(n+" klasör yeniden adlandırıldı.");scan.Enabled=true;await Scan();}}
}
